### ISSUE TITLE
Change in the title of alert box

### ISSUE THREAD

**Issue by reverie-ss** [addy-org/Addy-Android#22]
**I'm submitting a ...**

- [x] bug report
- [ ] feature request

**Current behavior:**

The "SearchByACode" alertbox, shows title "Type Your Message"

**Expected behavior:**

The "SearchByACode" alertbox,  title should be "Enter your ACode"

**Steps to reproduce:**
Open Addy application -> Click on "SearchByACode" button

**Comment by GOVINDDIXIT** [comment]
I will do it

**Comment by reverie-ss** [comment]
For getting an issue assigned, please,

1. First join the Gitter Chat for the specific project
2. Join the GitHub Organisation
3. Ask on the chatroom to get an issue assigned mentioning the issue URL

**Comment by yashovardhanagrawal** [comment]
@GOVINDDIXIT gitter channel link is given in the README.md file, you may join the chat there

at the top in the description section, joining link for GitHub organisation is mentioned, join the organisation from there. then ask on there to get the issue assigned.

CC @ihsraham
