### ISSUE TITLE
Remove Twitter Image Button From Sign in page

### ISSUE THREAD

**Issue by reverie-ss** [addy-org/Addy-Android#9]
**I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [x] Enhancement

**Current behavior:**
Twitter sign in is not working

**Expected behavior:**
Twitter Sign In should work

**Steps to reproduce:**
If logged in,
Open The app --> Log Out
If not logged in,
Open the app

**Comment by dylanmaryk** [comment]
Do you want the Twitter button to be removed, or for Twitter sign in to be fixed?
